apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykefravarsstatistikk-api
  namespace: default
  labels:
    team: teamtag
spec:
  image: navikt/sykefravarsstatistikk-api:5683d28ccf2198a22130af317087c5a5cc231e7b
  team: teamtag
  port: 8080
  ingresses:
    - https://arbeidsgiver.nais.preprod.local/sykefravarsstatistikk-api/
  liveness:
    path: /sykefravarsstatistikk-api/internal/healthcheck
    initialDelay: 20
  readiness:
    path: /sykefravarsstatistikk-api/internal/healthcheck
    initialDelay: 20
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
  prometheus:
    enabled: true
    path: /sykefravarsstatistikk-api/internal/actuator/prometheus
  webproxy: true
  vault:
    enabled: true
