apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykefravarsstatistikk-api
  namespace: default
  labels:
    team: arbeidsgiver
spec:
  image: navikt/sykefravarsstatistikk-api:3a8014100e31fe531eb9fa33e03bcb0b9c89d24c
  team: arbeidsgiver
  port: 8080
  ingresses:
    - https://arbeidsgiver.nais.preprod.local/sykefravarsstatistikk-api/
  liveness:
    path: /sykefravarsstatistikk-api/internal/healthcheck
    initialDelay: 30
  readiness:
    path: /sykefravarsstatistikk-api/internal/healthcheck
    initialDelay: 30
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
  prometheus:
    enabled: true
    path: /sykefravarsstatistikk-api/internal/actuator/prometheus
  webproxy: true
  vault:
    enabled: true
  resources:
    limits:
      memory: 1024Mi
    requests:
      memory: 512Mi
