server.servlet.context-path: /sykefravarsstatistikk-api

management.endpoints.web:
  exposure.include: info, health, metrics, prometheus
  base-path: /internal/actuator

  flyway:
    locations: classpath:/db/migration

spring:
  profiles:
    active: local
  h2.console:
    enabled: true
    path: /h2
  flyway:
    locations: classpath:/db/migration,/db/testdata
