server.servlet.context-path: /sykefravarsstatistikk-api

management.endpoints.web:
  exposure.include: info, health, metrics, prometheus
  base-path: /internal/actuator
  flyway:
    locations: classpath:/db/migration

spring:
  profiles:
    active: local

---

spring:
  profiles: local
  h2.console:
    enabled: true
    path: /h2
  flyway:
    locations: classpath:/db/migration,/db/testdata

mock:
  port: 8081

altinn:
  url: "http://localhost:${mock.port}/altinn/"
  apikey: "test"
  apigw.apikey: "test"
  iaweb.service:
    code: 3403
    edition: 1

no.nav.security.oidc:
  issuers: iss-localhost, selvbetjening
  issuer:
    iss-localhost:
      discoveryurl: http://metadata
      accepted_audience: aud-localhost
    selvbetjening:
      discoveryurl: http://metadata
      accepted_audience: aud-localhost

---

spring:
  profiles: mvc-test

no.nav.security.oidc:
  issuers: iss-localhost, selvbetjening
  issuer:
    iss-localhost:
      discoveryurl: http://metadata
      accepted_audience: aud-localhost
    selvbetjening:
      discoveryurl: http://metadata
      accepted_audience: aud-localhost

---

spring:
  profiles: dev

altinn:
  url: "https://api-gw-q1.adeo.no/"
  apikey: ${ALTINN_APIKEY}
  apigw.apikey: ${ALTINN_APIGW_APIKEY}
  iaweb.service:
    code: 3403
    edition: 1
---

spring:
  profiles: prod

altinn:
  url: "https://api-gw.adeo.no/"
  apikey: ${ALTINN_APIKEY}
  apigw.apikey: ${ALTINN_APIGW_APIKEY}
  iaweb.service:
    code: 3403
    edition: 2