server.servlet.context-path: /sykefravarsstatistikk-api

management.endpoints.web:
  exposure.include: info, health, metrics, prometheus
  base-path: /internal/actuator
  flyway:
    locations: classpath:/db/migration

spring:
  profiles:
    active: local

---

spring:
  profiles: local
  h2.console:
    enabled: true
    path: /h2

mock:
  port: 8081

altinn:
  url: "http://localhost:${mock.port}/altinn/"
  apikey: "test"
  apigw.apikey: "test"
  iaweb.service:
    code: 3403
    edition: 1

no.nav.security.oidc:
  issuers: iss-localhost, selvbetjening
  issuer:
    iss-localhost:
      discoveryurl: http://metadata
      accepted_audience: aud-localhost
    selvbetjening:
      discoveryurl: http://metadata
      accepted_audience: aud-localhost

applikasjon.datasource:
  url: jdbc:h2:mem:test
  username: SA
  password:
  driver-class-name: org.h2.Driver

datavarehus.datasource:
  url: jdbc:h2:mem:test
  username: SA
  password:
  driver-class-name: org.h2.Driver

---

spring:
  profiles: db-test

  flyway:
    locations: classpath:/db/migration,classpath:/db/test-datavarehus

applikasjon.datasource:
  url: jdbc:h2:mem:test
  username: SA
  password:
  driver-class-name: org.h2.Driver

datavarehus.datasource:
  url: jdbc:h2:mem:test
  username: SA
  password:
  driver-class-name: org.h2.Driver


---

spring:
  profiles: mvc-test

no.nav.security.oidc:
  issuers: iss-localhost, selvbetjening
  issuer:
    iss-localhost:
      discoveryurl: http://metadata
      accepted_audience: aud-localhost
    selvbetjening:
      discoveryurl: http://metadata
      accepted_audience: aud-localhost

altinn:
  url: "http://localhost:1331/altinn/"
  apikey: "test"
  apigw.apikey: "test"
  iaweb.service:
    code: 3403
    edition: 1

---

spring:
  profiles: dev

altinn:
  url: "https://api-gw-q1.adeo.no/"
  apikey: ${ALTINN_APIKEY}
  apigw.apikey: ${ALTINN_APIGW_APIKEY}
  iaweb.service:
    code: 3403
    edition: 1

database.navn: sykefravarsstatistikk
vault.mount-path: postgresql/preprod-fss

datavarehus.datasource:
  url: jdbc:oracle:thin:@dm07-scan.adeo.no:1521/dwhq0
  username: ${DVH_BRUKERNAVN}}
  password: ${DVH_PASSORD}
  driver-class-name: oracle.jdbc.driver.OracleDriver

---

spring:
  profiles: prod

altinn:
  url: "https://api-gw.adeo.no/"
  apikey: ${ALTINN_APIKEY}
  apigw.apikey: ${ALTINN_APIGW_APIKEY}
  iaweb.service:
    code: 3403
    edition: 2

database.navn: sykefravarsstatistikk
vault.mount-path: postgresql/prod-fss
