version: 2.1
jobs:
  build:
    docker:
    - image: circleci/openjdk:11
    steps:
    - checkout
    - restore_cache:
        keys:
          - maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
          - maven-repo-v1-{{ .Branch }}-
          - maven-repo-v1-
    - run:
          name: Bygger med Maven
          command: mvn clean package
    - save_cache:
        paths:
          - ~/.m2
        key: maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
    - setup_remote_docker
    - run:
        name: Bygger Docker image
        command: docker build -t "navikt/sykefravarsstatistikk-api:$CIRCLE_SHA1" .
    - run:
        context: NAIS deployment
        name: Pusher Docker image
        command: |
          echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
          docker push "navikt/kontakt-oss-api:$CIRCLE_SHA1"
          echo "Docker image: $CIRCLE_SHA1"